#' deal_cards
#'
#' @param deck {A deck of cards generated by create-cardDeck()}
#'
#' @return shuffled_deck {all cards are split on North, South, East, West}
#' @export
#'
#' @import dplyr
#'
deal_cards <- function(deck){
  shuffled_deck <- bind_cols(deck, hand = rep(c('N', 'Ö', 'S', 'V') , 13))
  shuffled_deck
}
